INSERT INTO products (name, price, unit, description) VALUES ('Wireless Mouse', 49.99, 'piece', 'High quality wireless mouse perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Gaming Keyboard', 89.99, 'unit', 'High quality gaming keyboard perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('LED Monitor', 129.99, 'pack', 'High quality led monitor perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('USB-C Cable', 9.99, 'box', 'High quality usb-c cable perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Bluetooth Speaker', 59.99, 'set', 'High quality bluetooth speaker perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Smartphone Case', 19.99, 'piece', 'High quality smartphone case perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Power Bank', 39.99, 'unit', 'High quality power bank perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Laptop Stand', 29.99, 'pack', 'High quality laptop stand perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Webcam', 69.99, 'box', 'High quality webcam perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Noise Cancelling Headphones', 149.99, 'set', 'High quality noise cancelling headphones perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Organic Apples', 3.49, 'kg', 'Fresh organic apples, juicy and crisp.');
INSERT INTO products (name, price, unit, description) VALUES ('Whole Grain Bread', 2.99, 'loaf', 'Healthy whole grain bread, freshly baked.');
INSERT INTO products (name, price, unit, description) VALUES ('Olive Oil', 10.99, 'bottle', 'Extra virgin olive oil, cold pressed.');
INSERT INTO products (name, price, unit, description) VALUES ('Pasta', 1.49, 'pack', 'Durum wheat pasta for perfect al dente.');
INSERT INTO products (name, price, unit, description) VALUES ('Coffee Beans', 8.99, 'bag', 'Premium coffee beans with rich aroma.');
INSERT INTO products (name, price, unit, description) VALUES ('Milk', 1.09, 'liter', 'Fresh whole milk, farm-produced.');
INSERT INTO products (name, price, unit, description) VALUES ('Chef Knife', 24.99, 'piece', 'High carbon steel chef knife for precision cutting.');
INSERT INTO products (name, price, unit, description) VALUES ('Cutting Board', 12.99, 'piece', 'Bamboo cutting board, durable and eco-friendly.');
INSERT INTO products (name, price, unit, description) VALUES ('Non-stick Pan', 29.99, 'piece', 'Non-stick frying pan for easy cooking and cleaning.');
INSERT INTO products (name, price, unit, description) VALUES ('Mixing Bowl Set', 19.99, 'set', 'Stainless steel mixing bowls set, various sizes.');
INSERT INTO products (name, price, unit, description) VALUES ('Office Chair', 159.99, 'piece', 'High quality office chair perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Standing Desk', 299.99, 'unit', 'High quality standing desk perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Backpack', 49.99, 'pack', 'High quality backpack perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Sunglasses', 29.99, 'box', 'High quality sunglasses perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Water Bottle', 14.99, 'set', 'High quality water bottle perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Notebook', 4.99, 'piece', 'High quality notebook perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Pen Set', 9.99, 'unit', 'High quality pen set perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Phone Tripod', 19.99, 'pack', 'High quality phone tripod perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Microphone', 79.99, 'box', 'High quality microphone perfect for everyday use.');
INSERT INTO products (name, price, unit, description) VALUES ('Graphic Tablet', 149.99, 'set', 'High quality graphic tablet perfect for everyday use.');

INSERT INTO coupons (code, amount, expiration) VALUES ('5%OFF', 5.00, '2026-01-01 23:59:59');
INSERT INTO coupons (code, amount, expiration) VALUES ('10%OFF', 10.00, '2025-12-24 23:59:59');
INSERT INTO coupons (code, amount, expiration) VALUES ('15%OFF', 15.00, '2025-12-24 23:59:59');
INSERT INTO coupons (code, amount, expiration) VALUES ('20%OFF', 20.00, '2025-12-24 23:59:59');
INSERT INTO coupons (code, amount, expiration) VALUES ('25%OFF', 25.00, '2025-06-01 00:00:00');
